export const exp = [
    {
        image: "exp/1.png",
        title: "Consulting & Digital Solutions",
        Sous_title: "CDS",
        text:"Des solutions innovantes face aux enjeux de la transformation digitale. Fort de nos expertises en conseil stratégique et mise en œuvre de solutions à forte valeur ajoutée, nous accompagnons les entreprises dans leur recherche de compétitivité.",
        url:"#",
        isShowing : true,
        Text_btn:"En savoir +",
    },
    {
        image: "exp/2.png",
        title: "Cybersécurité",
        Sous_title: "Cybersecurité",
        text:"",
        url:"#",
        isShowing : false,
        Text_btn:"En savoir +",
    },
    {
        image: "exp/3.png",
        title: "Assur’Tech",
        Sous_title: "AssurTech",
        text:"L’AssurTech, qui réinvente l’audit, le conseil et la pratique dans les métiers de l’assurance, par des solutions technologiques et digitales à forte dimension d’innovation.",
        url:"#",
        isShowing : true,
        Text_btn:"En savoir +",
    },
    {
        image: "exp/4.png",
        title: "RH & Recrutement",
        Sous_title: "RH & Recrutement",
        text:"Des consultants experts d’expérience, associés à des solutions technologiques de dernière génération, au service d’une prestation globale de conseil en ressources humaines et recrutement.",
        url:"#",
        isShowing : true,
        Text_btn:"En savoir +",
    },
    {
        image: "exp/5.png",
        title: "Solutions TPE / PME",
        Sous_title: "Solutions TPE-PME",
        text:"Des solutions pour les TPE et PME qui aspirent à transformer leurs métiers par le biais du digital. Nos produits et services sont parfaitement adaptés à vos problématiques et besoins.",
        url:"#",
        isShowing : true,
        Text_btn:"En savoir +",
    },
    {
        image: "exp/6.png",
        title: "Events & Destination Management",
        Sous_title: "DMC",
        text:"L’agence conseil en management de l’événementiel et du voyage d’entreprises, engagée dans la conception et l’exécution d’événements inédits et sur mesure, intégrant la gestion réceptive associée. ",
        url:"#",
        isShowing : true,
        Text_btn:"En savoir +",
    },
    {
        image: "exp/7.png",
        title: "Start-up Studio",
        Sous_title: "Imag!ne",
        text:"Imag!ne, c’est transformer l’imagination en innovation. Un pool unique de compétences capitalisant sur les expériences et les expertises du groupe MENAPS, au service d’entrepreneurs de tous horizons.",
        url:"#",
        isShowing : true,
        Text_btn:"En savoir +",
    },
    {
        image: "exp/8.png",
        title: "Marketing & Communication",
        Sous_title: "Brand Cap",
        text:"Une offre intégrale de conseil, stratégique, créative et opérationnelle placée au cœur du processus de transformation digitale",
        url:"#",
        isShowing : true,
        Text_btn:"En savoir +",
    },
    {
        image: "exp/9.png",
        title: "Solutions Connectées",
        Sous_title: "Solutions connectées",
        text:"",
        url:"#",
        isShowing : false,
        Text_btn:"En savoir +",
    },
]